### ISSUE TITLE
Share button crashes the app on 14.8.1 (checkra1n/odysseyra1n)

### ISSUE THREAD

**Issue by Rov3r** [0xkuj/IPARanger#1]
I have an iPad Pro 1st gen (A9X) on 14.8.1 OdysseyRa1n (also tried on Checkra1n), and the app always crashes when tapping the share button on a downloaded ipa.

**Comment by 0xkuj** [comment]
which version did you tried? i fixed some crashes related to ipad in version 1.4

**Comment by Rov3r** [comment]
I have 1.4. Initially tried it on checkra1n then restored the system and jailbroke with odysseyra1n and got the same result. Both were on 1.4On Mar 28, 2023, at 2:22 AM, Omri ***@***.***> wrote:﻿
which version did you tried? i fixed some crashes related to ipad in version 1.4

**Comment by 0xkuj** [comment]
you can open in filza and share the file as a workaround while i will work on a fix

**Comment by Rov3r** [comment]
Thanks, I’ve been using this in the meantime. Although now I’m trying to sign decrypted apps and they won’t open when sideloaded on a paid dev account nor when installed through TrollStore. Not on my iPhone nor this iPad.On Mar 28, 2023, at 4:55 PM, Omri ***@***.***> wrote:﻿
you can open in filza and share the file as a workaround while i will work on a fix

**Comment by 0xkuj** [comment]
How are you trying to decrypt those downloaded apps?

**Comment by davylijing** [comment]
Where can I download it

**Comment by Rov3r** [comment]
Yes I thought the downloaded ipa was decrypted. Is it not? Even if it isn’t, shouldn’t it still open when installed via TrollStore on the iPad?

**Comment by 0xkuj** [comment]
They are not decrypted and you can’t install apps that are not decrypted in TrollStore. Use other tools to decrypt them like iridium or crackerxi
