### ISSUE TITLE
Error no directory

### ISSUE THREAD

**Issue by Surmavanick** [0xkuj/IPARanger#12]
![151B4F6B-AB9D-47C8-95F9-AFBB0758FBDE](https://github.com/0xkuj/IPARanger/assets/138652096/5220f606-36cc-467e-8134-22b980051752)

cant login on Xina jailbreak. using Sileo and trollstore.  ios15.1

**Comment by 0xkuj** [comment]
IPARanger does not support Xina. Please consider moving to dopamine.
