### ISSUE TITLE
Crash on roothide jailbreak

### ISSUE THREAD

**Issue by 1abd135** [0xkuj/IPARanger#13]
The app crashs when I click on sign in

**Comment by 0xkuj** [comment]
Which jailbreak and iOS?

**Comment by 1abd135** [comment]
Dopamine roothide

**Comment by 1abd135** [comment]
- works well with dopamine rootless

**Comment by 0xkuj** [comment]
I am working on support for roothide, it is not supported yet.

**Comment by langkhach270389** [comment]
Yeah. Wating fix crash downloaded tab finished

**Comment by 0xkuj** [comment]
Did you try the latest version from roothide repo?

**Comment by langkhach270389** [comment]
> Did you try the latest version from roothide repo?

yeah. i am latest version. crash. 
Using rootless deb converted. Fine. don't crash

**Comment by 0xkuj** [comment]
please try the new arm64e deb i uploaded just now in release section and let me know https://github.com/0xkuj/IPARanger/releases/download/1.8/com.0xkuj.iparanger_1.8_iphoneos-arm64e.deb

**Comment by langkhach270389** [comment]
> please try the new arm64e deb i uploaded just now in release section and let me know https://github.com/0xkuj/IPARanger/releases/download/1.8/com.0xkuj.iparanger_1.8_iphoneos-arm64e.deb


Click download tab > crash

**Comment by 0xkuj** [comment]
Can you provide a crash log?

**Comment by 1abd135** [comment]
I'had clear crashlogs 
But it works well after converting with "Patcher" using rootless compact layer
