### ISSUE TITLE
non jailbreak

### ISSUE THREAD

**Issue by emreozcn06** [0xkuj/IPARanger#14]
appsotore deki uygulama ve oyunların güncel sürümlerini jb olmayan bir cihaz ile almanın bir yolu yokmu ?
bu işlemi ücretli yapan websiteleri mevcut fakat fiyatlar pahalı bunun uygun bir yolu yokmu ?

**Comment by 0xkuj** [comment]
you cant run this app on nonjailbroken iphone as this requires to run shell commands
