### ISSUE TITLE
Application Search Error

### ISSUE THREAD

**Issue by kuang123321** [0xkuj/IPARanger#19]
![Uploading 7B380161-C9D4-4621-A0CF-33A925425217.jpeg…]()

**Comment by kuang123321** [comment]
![Uploading CEC5E348-6B57-4FCA-8028-C20C39159BCA.jpeg…]()

**Comment by 0xkuj** [comment]
@kuang123321 images doesnt work.. reupload them please

**Comment by 0xkuj** [comment]
closing as no comment, i cant see the images 
please reopen if needed
