### ISSUE TITLE
paste crash

### ISSUE THREAD

**Issue by lqr1** [0xkuj/IPARanger#6]
so basically when i click on the paste button the app will start crashing and glitching im on ios 15.1 (dopamine) 

https://github.com/0xkuj/IPARanger/assets/128184565/b190a236-8383-4e0d-899c-9eb149e99134

**Comment by 0xkuj** [comment]
fixed in 1.7

**Comment by lqr1** [comment]
> fixed in 1.7

its not on ur repo or updated on havoc repo 
rootless jailbreak

**Comment by 0xkuj** [comment]
It is in here https://github.com/0xkuj/IPARanger/tree/main/packages and soon will be approved by havoc, by Monday probably
